### ISSUE TITLE
Does not work anymore with RM8

### ISSUE THREAD

**Issue by fabn** [basgren/rubymine-injector#1]
I was used to this awesome plugin, however it seems to be broken on RubyMine 8, projects doesn't load anymore after installation.

**Comment by basgren** [comment]
Thanks for letting me know, and I'm glad that the plugin is still useful! :)
I already spotted the exception which crashed the IDE, but I need to look closer. I hope I'll have more time next few days to continue investigation. 
Thanks!

**Comment by basgren** [comment]
Hi. I have updated plugin to version 1.03 - it should work with RM8. Please check.

**Comment by fabn** [comment]
It works indeed, thank you very much.
