### ISSUE TITLE
Cannot save changed templates in plugin settings

### ISSUE THREAD

**Issue by fabn** [basgren/rubymine-injector#2]
I'm trying to change templates in plugin preferences however when I change something and save the next time I reopen the preferences panel I found same values as before.

I want to remove the dashes in default configuration because they [are not needed anymore](http://www.kuwata-lab.com/erubis/users-guide.06.html#topics-trimspaces) so for instance `<%- end -%>` should become `<% end %>`.

Alternatively may I ask you to change default values for your plugin to remove dashes. They causes some issues in `js.erb` templates and I have to remove them by hand.

Could you help me?

**Comment by basgren** [comment]
Thanks for letting me know. As far as I remember, you use RubyMine 8, right?
I hope I'll be able to look at the issue this weekend.

Also I agree that dashes can be removed in default config - at the time when I released the initial version of the plugin, using dashes was more like a personal preference. And one more question - I don't follow Ruby development for about a year (new big project is in node.js), so could you please tell me if these dashes are not needed at all now? I mean even with default .erb processor bundled with RoR.

Thank you

**Comment by fabn** [comment]
> Thanks for letting me know. As far as I remember, you use RubyMine 8, right?

That's correct.

> And one more question - I don't follow Ruby development for about a year (new big project is in node.js), so could you please tell me if these dashes are not needed at all now?

Yes, they are not needed anymore and they are even discouraged by some guides and some code style checkers.

Also when using them in `.js.erb` assets they cause syntax errors, for instance if you have an asset like this

``` erb
var _appConfig = {
    accessToken: "<%= ENV['CLIENT_TOKEN'] -%>"
};
```

it will raise this error

```
syntax error, unexpected ')'
...concat(( ENV['CLIENT_TOKEN'] -).to_s); _erbout.concat "\",\n"
                               ^^^
...                        
```

because the final dash is replicated in erb output.

**Comment by basgren** [comment]
Hi, @fabn ! I've updated the plugin - indeed saving in IDE Settings was broken (btw, settings also can be opened by right-click on injector icon in IDE status bar).
Also I have updated default templates. No more dashes by default :)

**Comment by fabn** [comment]
Thank you very much. I'll try it as soon as possible.
