### ISSUE TITLE
Provide tooltip to the nozzle icon

### ISSUE THREAD

**Issue by bwolf** [basgren/rubymine-injector#3]
A tooltip would greatly enhance the usability. It should also contain information from which plugin (Injector) the statusbar icon comes from. I run into the issue that for some reason I had this plugin installed and had no clue what the icon is for.

**Comment by basgren** [comment]
No problem! Will add tooltip :)
Thanks! Just glad that someone is still using this plugin :)

**Comment by bwolf** [comment]
Issue seems to be dead

**Comment by basgren** [comment]
Oh my... I'm so sorry for being so sloooow. I've updated the plugin to version 1.05 which has tooltip. Better late than never ;)
